-- This module is the root of the AnabelianGeometryCanonicalLaneLean Lean proof package.
import AnabelianGeometryCanonicalLaneLean.Basic
import AnabelianGeometryCanonicalLaneLean.SourcePackage
import AnabelianGeometryCanonicalLaneLean.SourceDependencies
import AnabelianGeometryCanonicalLaneLean.Formalization
import AnabelianGeometryCanonicalLaneLean.ReviewerBridge
import AnabelianGeometryCanonicalLaneLean.TheoremStatement
import AnabelianGeometryCanonicalLaneLean.MathlibObjects
import AnabelianGeometryCanonicalLaneLean.AdmissibleClass
import AnabelianGeometryCanonicalLaneLean.Projection
import AnabelianGeometryCanonicalLaneLean.BridgeLemmas
import AnabelianGeometryCanonicalLaneLean.GateLemmas
import AnabelianGeometryCanonicalLaneLean.FinalTheorem
import AnabelianGeometryCanonicalLaneLean.MathlibStatement
